# Commands to start on workspace startup
image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install
    command: npm run develop
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview